#!/usr/bin/env bash
# install and configure HAproxy on lb-01
sudo apt-get update
sudo apt-get -y install haproxy

sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOT
frontend http-in
	bind *:80
	mode http
	default_backend servers
backend servers
	mode http
	balance roundrobin
	server 104666-web-01 3.84.238.176:80 check
	server 104666-web-02 52.87.233.7:80 check
EOT
sudo /etc/init.d/haproxy start
#boot the server
sudo update-rc.d haproxy defaults
sudo /etc/int.d/haproxy reload
