#!/usr/bin/env bash
# Displays "Best School" x10 but the 9th displays
#Best School and then Hi

index=0

while [ $index -lt 10 ]
do
if [ $index -eq 9 ]
then
echo "Hi"
fi
echo "Best School"
index=$((index+1))
done
