#!/usr/bin/env bash
#Displays numbers 1 to 20 and:
# 4 and then bad luck from china on 4th loop iteration
# 9 and then bad luck from Japan on 9th loop iteration
# 17 and then bad luck from italy on 17th loop iteration

count=1

while [ $count -le 20 ]
do
echo "$count"
case $count in
"4") echo "bad luck from China";;
"9") echo "bad luck from Japan";;
"17") echo "bad luck from italy";;
esac
count=$((count+1))
done
